"""Generate documentation from node declarations without creating any nodes.

Run from the repository root with: python tools/generate_node_inventory.py
"""
from pathlib import Path
import sys
import json

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
import register
from graph_document import local_value
from persistence import encode_value


def render() -> str:
    """Describe persistent policy, defaults and ports from registered classes."""
    register.reload_node_registry()
    lines = ['# Built-in parameter and port inventory', '',
             'Generated by `python tools/generate_node_inventory.py` from node-owned declarations.',
             'This is documentation only, not a runtime catalog or loader input. No nodes are constructed.',
             'Defaults are typed JSON values. Event ports have no stored value.',
             'See the [contract](contract.md) and [implementation guide](implementation.md).', '']
    for name, cls in sorted(register.node_registry.items()):
        if not cls.__module__.startswith('eventnodes.'):
            continue
        path = cls.__module__.replace('.', '/') + '.py'
        lines += [f'## {name}', '', f'Source: [{path}](../../{path})', '',
                  '| Binding | Class | Flags | Policy | Default |', '| --- | --- | --- | --- | --- |']
        for key, definition in sorted(cls.describe_parameters().items()):
            default = json.dumps(encode_value(local_value(definition.create(None))), ensure_ascii=False) if definition.storage == 'stored' else 'not stored'
            fields = [key, definition.factory.__name__, str(definition.options['pluggable']), definition.storage, default]
            lines.append('| ' + ' | '.join('`' + field.replace('|', '&#124;') + '`' for field in fields) + ' |')
        for key, (_, flags) in cls.signal_definitions.items():
            lines.append(f'| `event:{key}` | `Signal` | `{flags}` | event port | no value |')
        if cls.dynamic_input_prefix:
            lines += ['', f'Dynamic input family: `{cls.dynamic_input_prefix}N`, starting at 1.']
        for key, field in cls.state_fields.items():
            lines += ['', f'Extra persistent state: `{key}` maps to `{field.attribute}`.']
        lines.append('')
    return '\n'.join(lines)


if __name__ == '__main__':
    (ROOT / 'docs/persistence/builtin-inventory.md').write_bytes(render().encode('utf-8'))
